name: Close Stale Pull Requests
on:
  workflow_call: # Can be invoked as a reusable workflow
    inputs:
      days-before-pr-stale:
        description: 'Number of days with no activity before a PR is marked stale'
        default: 15
        required: false
        type: number
      days-before-pr-close:
        description: 'Number of days with no activity before a stale PR is closed'
        default: 7
        required: false
        type: number
  workflow_dispatch: # Can be triggered manually
  schedule: # Runs once every day, in the late morning
    - cron: "41 16 * * *" # 15:41 UTC / 10:41 AM EST (UTC-5) / 11:41 AM EDT (UTC-4)

jobs:
  close-stale-prs:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v4
        with:
          days-before-issue-stale: -1
          days-before-issue-close: -1
          stale-pr-message: "This pull request was marked stale because it has been open for ${{ inputs.days-before-pr-stale }} days with no activity. It will be closed automatically in ${{ inputs.days-before-pr-close }} days if it remains idle. Consider converting it to a draft if you aren't ready to merge it."
          close-pr-message: "This pull request was closed because it has been inactive for ${{ inputs.days-before-pr-close}} days since being marked as stale."
          days-before-pr-stale: ${{ inputs.days-before-pr-stale }}
          days-before-pr-close: ${{ inputs.days-before-pr-close }}
          exempt-draft-pr: true
          operations-per-run: 5000
          repo-token: ${{ secrets.GITHUB_TOKEN }}

